name: 4diac IDE verification build

on:
  push:
    branches: [ "release", "develop", "freeze", "3.0.x"]
  pull_request:
    branches: [ "release", "develop", "freeze", "3.0.x"]

jobs:
  event_file:
    name: "Upload Event File"
    runs-on: ubuntu-latest
    steps:
    - name: Upload
      uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4.4.3
      with:
        name: event_file
        path: ${{ github.event_path }}
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        java: [21]
    runs-on: ${{ matrix.os }} 
    name: OS ${{ matrix.os }} Java ${{ matrix.java }} compile
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - name: Set up Java
      uses: actions/setup-java@8df1039502a15bceb9433410b1a100fbe190c53b # v4.5.0
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java }}
        cache: 'maven'
    - name: Set up Maven
      uses: stCarolas/setup-maven@d6af6abeda15e98926a57b5aa970a96bb37f97d1 # v5
      with:
        maven-version: 3.9.6
    - name: Build with Maven
      uses: coactions/setup-xvfb@b6b4fcfb9f5a895edadc3bc76318fae0ac17c8b3 # v1.0.1
      with:
       run: >- 
        mvn -V -B -fae -ntp clean verify
    - name: Upload Test Results for Java-${{ matrix.java }}
      if: always()
      uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4.4.3
      with:
        name: test-results-${{ matrix.os }}-java${{ matrix.java }}
        if-no-files-found: error
        path: |
          ${{ github.workspace }}/**/target/surefire-reports/*.xml
